"""
Django settings for esodawebsite project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from decouple import config, Csv
import dj_database_url
from django.utils.translation import ugettext_lazy as _


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Registration settings

REGISTRATION_OPEN = config('REGISTRATION_OPEN', default=True, cast=bool)
ACCOUNT_ACTIVATION_DAYS = 30
INCLUDE_AUTH_URLS = True
INCLUDE_REGISTER_URL = True
REGISTRATION_AUTO_LOGIN = False
REGISTRATION_FORM = 'authentication.forms.RegistrationFormEmailAsUsername'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Note: SECRET_KEY doesn't have a default value and must be set in `.env`
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='False', cast=bool)

INTERNAL_IPS = ('127.0.0.1',)

ADMINS = config('ADMINS', default='', cast=lambda s: [pair.split(',') for pair in s.strip().split(';')])

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv(post_process=tuple))

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'authentication',
    'registration',
    'common',
    'esoda',
    'widget_tweaks',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Security settings

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'


ROOT_URLCONF = 'esodawebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'esodawebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL')
    )
}


# Logging
# Will be merged with django's DEFAULT_LOGGING settings

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(levelname)s] [%(asctime)s] %(name)s %(process)d %(thread)d - %(message)s'
        },
        'simple': {
            'format': '[%(levelname)s] [%(asctime)s] %(name)s - %(message)s'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'filters': ['require_debug_false'],
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(config('LOGGING_DIR', default='.'), 'runtime.log'),
            'maxBytes': 1024 * 1024 * 500,
            'backupCount': 20,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'root': {
        'level': 'INFO',
        'handlers': ['console', 'file', 'mail_admins'],
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': config('MIN_PASSWORD_LENGTH', default='1', cast=int),
        }
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-CN'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ('en', _('English')),
    ('zh-hans', _('Simplified Chinese')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

if os.path.isdir(STATIC_ROOT):
    CSS_STYLE_VERSION = '%d' % os.path.getmtime(os.path.join(STATIC_ROOT, 'css', 'style.css'))
    JS_ESODA_INDEX_VERSION = '%d' % os.path.getmtime(os.path.join(STATIC_ROOT, 'js', 'esoda-index.js'))
    JS_ESODA_RESULT_VERSION = '%d' % os.path.getmtime(os.path.join(STATIC_ROOT, 'js', 'esoda-result.js'))
    JS_ESODA_MAIN_VERSION = '%d' % os.path.getmtime(os.path.join(STATIC_ROOT, 'js', 'esoda-main.js'))


# Email configuration

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
DEFAULT_FROM_EMAIL = SERVER_EMAIL = 'Esoda <%s>' % EMAIL_HOST_USER


# Esoda esearch configuration

ELASTICSEARCH_HOST = config('ELASTICSEARCH_HOST')
# ELASTICSEARCH_INDEX = config('ELASTIC_INDEX', default='dblp')
# ELASTICSEARCH_DOCTYPE = config('ELASTIC_DOCTYPE', default='sentences')


# Mongodb configuration

MONGODB_HOST = config('MONGODB_HOST')
MONGODB_USER = config('MONGODB_USER', default='')
MONGODB_PASSWORD = config('MONGODB_PASSWORD', default='')


# Stanford CoreNLP configuration

STANFORD_CORENLP_SERVER = config('STANFORD_CORENLP_SERVER', default='http://corenlp.run/')


# Youdao API configuration
YOUDAO_APP_KEY = config('YOUDAO_APP_KEY', default='')
YOUDAO_SECRET_KEY = config('YOUDAO_SECRET_KEY', default='')


# Slack Webhook URL
SLACK_WEBHOOK_URL = config('SLACK_WEBHOOK_URL', default='')
SLOW_RESPONSE_LOG_TIME = config('SLOW_RESPONSE_LOG_TIME', default=0.5, cast=float)
SLOW_RESPONSE_WARNING_TIME = config('SLOW_RESPONSE_WARNING_TIME', default=5.0, cast=float)
