# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('c_id', models.IntegerField(verbose_name='id')),
                ('deep_level', models.IntegerField(default=0, verbose_name='depth')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='authentication.Corpus', verbose_name='parent')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='corpus_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='authentication.Corpus', verbose_name='domain'),
        ),
    ]
