# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170607_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='c_id',
            field=models.IntegerField(verbose_name='c_id'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='corpus_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='authentication.Corpus', verbose_name='domain'),
        ),
    ]
